spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${PUBLIC_IP}/${DB_NAME}?cloudSqlInstance=${CLOUDSQL_INSTANCE}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useUnicode=true&characterEncoding=&useSSL=true&serverTimezone=UTC"
    username: ${DB_USERNAME}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 20MB

server:
  port: 8080     # Spring의 기본 포트는 8080
  address: 0.0.0.0       # 외부에서 접근 가능

  error:
    include-message: always          # 예외 메시지 포함
    include-binding-errors: always   # 바인딩(검증) 에러도 포함
    include-stacktrace: on_param     # URL에 ?trace=true 붙였을 때만 스택트레이스 표시

#openai:
#  api-key: ${OPENAI_API_KEY}

logging:
  level:
    org.springframework.core.env: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,env
  endpoint:
    health:
      probes:
        enabled: true
